import requests
from bs4 import BeautifulSoup

USER_AGENT = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'}


def get_html(search_term, number_results):
    """
    Get the results (HTML) from Google search page based on the search term defined and the number os results needed
    
    Params:
    - search_term: String with the search term to be used
    - number_results: Integer representing the number os results needed
    
     Returns:
    - String with the HTML of the page searched
    """
    escaped_search_term = search_term.replace(' ', '+')
    google_url = 'https://www.google.com/search?q={}&num={}'.format(escaped_search_term, number_results)
    response = requests.get(google_url, headers=USER_AGENT)
    response.raise_for_status()

    return response.text

def format_result(html):
    """
    Format the results (HTML) received to extract the relevant information
    
    Params:
    - html: String containing the HTML of the Google search result
    
     Returns:
    - Dictionare with title,link and text insight from each result found with Google
    """
    soup = BeautifulSoup(html, 'html.parser')
    found_results = []
    all_results = soup.find_all('div', attrs={'class': 'g'})
    for result in all_results:
        link = result.find('a', href=True)
        title = result.find('h3')
        text_insight = result.find('span', attrs={'class': 'st'})
        link = link['href']
        title = title.get_text()
        if text_insight:
            text_insight = text_insight.get_text()
        else:
            text_insight = 'No text_insight found.'
        if link != '#':
            found_results.append({'title': title, 'text_insight': text_insight, 'link': link})
    
    return found_results

def get_text_insights(search_string):
    """
    Returns a list of text insights from the top 5 google results of the query generated by the keywords input
    
    Params:
    - search_string: String containing the keyword to be used on the search
    
     Returns:
    - Array with all the results found with the search_string
    """
    try:
        html = get_html(search_string, 5)
        results = format_result(html)
        return results
    except Exception as e:
        return e
    